---
name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: hadolint — alpine
        run: docker run --rm -i hadolint/hadolint < images/alpine/Dockerfile

      - name: hadolint — debian
        run: docker run --rm -i hadolint/hadolint < images/debian/Dockerfile

      - name: hadolint — ubuntu
        run: docker run --rm -i hadolint/hadolint < images/ubuntu/Dockerfile

      - name: actionlint
        uses: rhysd/actionlint@a443f344ff32813837fa49f7aa6cbc478d770e62  # v1.7.9

      - name: zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa  # v0.5.7

      - name: gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7  # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
